# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to build and deploy Application Only
# See readme file for info about variable group "FunctionDemo"
# ------------------------------------------------------------------------------------------------------------------------
parameters:
- name: environments
  type: object
  default: ['DEV']
- name: variableGroupName
  default: 'myVariableGroupName'
- name: runSecurityDevOpScan
  type: boolean
  default: false

# ----------------------------------------------------------------------------------------------------
stages:
- stage: BuildApplication
  displayName: Build Application
  jobs:
  - template: templates/secure-devops-template.yml
    parameters:
      environmentName: 'DEV'
      runSecurityDevOpScan: ${{ parameters.runSecurityDevOpScan }}

  - template: templates/build-function-template.yml
    parameters:
      variableGroupName: ${{ parameters.variableGroupName }}
      environmentName: 'DEV'

# ----------------------------------------------------------------------------------------------------
- ${{ each environmentName in parameters.environments }} :
  - stage: DeployApp${{ environmentName }}
    displayName: Deploy ${{ environmentName }} Application
    jobs:
    - template: templates/deploy-function-template.yml
      parameters:
        variableGroupName: ${{ parameters.variableGroupName }}
        environmentName: ${{ environmentName }}
