# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to deploy Azure Resources Only
# See readme file for info about variable group "FunctionDemo"
# ------------------------------------------------------------------------------------------------------------------------
parameters:
- name: environments
  type: object
  default: ['DEV']
- name: variableGroupName
  default: 'myVariableGroupName'
- name: runSecurityDevOpScan
  type: boolean
  default: false

# ----------------------------------------------------------------------------------------------------
stages:
- stage: ScanApplication
  displayName: Scan Application
  jobs:
  - template: templates/secure-devops-template.yml
    condition: runSecurityDevOpScan
    parameters:
      environmentName: 'DEV'

- ${{ each environmentName in parameters.environments }} :
  - stage: CreateInfrastructure${{ environmentName }}
    displayName: ${{ environmentName }} Infrastructure
    jobs:
    - template: templates/create-infra-template.yml
      parameters:
        variableGroupName: ${{ parameters.variableGroupName }}
        environmentName: ${{ environmentName }}
