# ----------------------------------------------------------------------------------------------------
# Pipeline used by the azd command
# ----------------------------------------------------------------------------------------------------
name: durable.function.demo

infra:
    provider: bicep
    path: infra
    module: main

pipeline:
    provider: github

services:
  function:
    project: src/AzureFunctionsDemo
    language: csharp
    host: function
