# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to deploy Azure Resources Only
# ------------------------------------------------------------------------------------------------------------------------
# Note: This pipeline needs a variable group "FunctionDemo"
#  See ../Docs/Create-Variable-Group.md for details
# ------------------------------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)
pool:
  vmImage: ubuntu-latest

# ------------------------------------------------------------------------------------------------------------------------
trigger:
  branches:
    include: 
      - main
  paths:
    include: 
      - '**/*.yml'
      - '**/*.yaml'
      - '**/*.bicep'

# ----------------------------------------------------------------------------------------------------
stages:
- template: pipes/infra-only-pipeline-template.yml
  parameters:
    variableGroupName: 'FunctionDemo'
    environments: ['DEMO']  # ['DEV','PROD'] ['DEV','QA'] or ['DEV','QA','PROD']
    runSecurityDevOpScan: false  # throws lots of warnings from PSRule that I don't care about
