# ----------------------------------------------------------------------------------------------------
# Pipeline to deploy all Azure Resources for one environment for the Azure Function Example Project
# ----------------------------------------------------------------------------------------------------
parameters:
  variableGroupName: 'myVariableGroup'
  environmentUpper: 'DEV'
  runDateTime: '12-31-2020 23:59:59'

# ----------------------------------------------------------------------------------------------------
jobs:
  - deployment: DeployEnvironment
    displayName: 'Initialize Deploy'
    environment: $(environmentUpper)
  - job: Deploy_Job
    displayName: Deploy Environment
    variables:
      - group: ${{ parameters.variableGroupName }}

    steps:
    # This is sooooo close, but I still can't get it to work right!
    #   Latest error: No HTTP resource was found that matches the request URI 'https://management.azure.com/subscriptions/a0f86c93-146a-4534-b83e-49090394aa78/resourcegroups/rg_functiondemo_dev/providers/Microsoft.Resources/resourceGroups/rg_functiondemo_dev?api-version=2020-06-01'
    # - task: AzureResourceGroupDeployment@2
    #   inputs:
    #     action: 'Create Or Update Resource Group'
    #     azureSubscription: $(subscriptionName)
    #     resourceGroupName: $(resourceGroupName)
    #     location: $(location)
    #     deploymentMode: 'Incremental'
    #     templateLocation: 'Linked artifact'
    #     csmFile: 'DeployToAzure/Arm/resourceGroup.json'
    #     overrideParameters: -rgName $(resourceGroupName) -rgLocation $(location)

    #- script: az bicep build --file DeployToAzure/Bicep/main.bicep --outfile DeployToAzure/Bicep/main.json
    #  displayName: 'Compile main Bicep file to ARM'

    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'Deploy ARM Templates'
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: '$(subscriptionName)'
        subscriptionId: '$(subscriptionId)'
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(resourceGroupName)'
        location: '$(location)'
        templateLocation: 'Linked artifact'
        csmFile: 'DeployToAzure/Bicep/main.bicep'
        overrideParameters: '-environmentCode $(environmentCode) -location $(location) -orgPrefix $(orgPrefix) -appPrefix $(appPrefix) -appSuffix $(appSuffix) -storageSku $(storageSku) -functionAppSku $(functionAppSku) -functionAppSkuFamily $(functionAppSkuFamily) -functionAppSkuTier $(functionAppSkuTier) -runDateTime ${{parameters.runDateTime}}'
        deploymentMode: 'Incremental'
        continueOnError: ignoreError
