# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to deploy Azure Resources for All Environments
# ------------------------------------------------------------------------------------------------------------------------
# Note: This pipeline needs a variable group "FunctionDemo-Infra-<env>" -> for EACH environment -> with these variables:
#   orgPrefix:            '<org / your initials>'
#   appPrefix:            'funcdemo'
#   environmentCode:      'dev/qa/prod'
#   resourceGroupName:    'rg_<prefix>_<envCode>'
#   subscriptionName:     '<ServiceConnectionName>'
#   subscriptionId:       '<subscriptionId>'
#   location:             'eastus'
#   appSuffix:            ''
#   storageSku:           'Standard_LRS'
#   functionAppSku:       'Y1'
#   functionAppSkuFamily: 'Y'
#   functionAppSkuTier:   'Dynamic'
#   keyVaultOwnerUserId1: '<userGuid>' // Future enhancement: email address
#   keyVaultOwnerUserId2: '<userGuid>' // Future enhancement: email address
#   acrName:              '<bicep container registry name>'
#   acrPassword:          '<bicep container admin password>'
#   acrPrincipalId:       '<service principal id with access to bicep container registry>'
#   acrTenantId:          '<service principal tenant id>'
#   acrPrincipalSecret:   '<service principal client secret>'
# ------------------------------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)
pool:
  vmImage: ubuntu-latest

# ------------------------------------------------------------------------------------------------------------------------
#trigger: none # only fire this manually
trigger:
  paths:
    include: 
      - '**/*.yml'
      - '**/*.yaml'
      - '**/*.bicep'

# ----------------------------------------------------------------------------------------------------
stages:
- stage: DeployDEVResources
  displayName: DEV Deploy Resources
  jobs:
  - template: Deploy-Bicep.yml
    parameters:
      variableGroupName: 'FunctionDemo-Infra-Dev'
      environmentUpper: 'DEV'
      runDateTime: 'Pipeline-$(Build.BuildNumber)'

# ----------------------------------------------------------------------------------------------------
- stage: DeployQAResources
  displayName: QA Deploy Resources
  dependsOn: DeployDEVResources
  condition: succeeded('DeployDEVResources')
  jobs:
  - template: Deploy-Bicep.yml
    parameters:
      variableGroupName: 'FunctionDemo-Infra-QA'
      environmentUpper: 'QA'
      runDateTime: 'Pipeline-$(Build.BuildNumber)'
