# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to build and deploy Azure Resources and Application
# See readme file for info about variable group "DurableDemo"
# ------------------------------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)

trigger:
  - none
  # batch: true
  # branches:
  #   include:
  #     - main
  #   exclude:
  #     - '**/*.md'

pool:
  vmImage: 'ubuntu-latest'

# ----------------------------------------------------------------------------------------------------
stages:
- stage: BuildApplication
  displayName: Build Application
  jobs:
  - template: templates/build-function-template.yml
    parameters:
      variableGroupName: 'FunctionDemo'
      environmentName: 'DEV'

# ----------------------------------------------------------------------------------------------------
- stage: DeployDEVInfra
  displayName: DEV Infra
  dependsOn: BuildApplication
  condition: succeeded('BuildApplication')
  jobs:
  - template: templates\deploy-bicep-template.yml
    parameters:
      variableGroupName: 'FunctionDemo'
      environmentName: 'DEV'

- stage: DeployDEVApp
  displayName: DEV App
  dependsOn: DeployDEVInfra
  condition: succeeded('DeployDEVInfra')
  jobs:
  - template: templates/deploy-function-template.yml
    parameters:
      variableGroupName: 'FunctionDemo'
      environmentName: 'DEV'


# ----------------------------------------------------------------------------------------------------
- stage: DeployQAInfra
  displayName: QA Infra
  dependsOn: DeployDEVApp
  condition: succeeded('DeployDEVApp')
  jobs:
  - template: templates\deploy-bicep-template.yml
    parameters:
      variableGroupName: 'FunctionDemo'
      environmentName: 'QA'

- stage: DeployQAApp
  displayName: QA App
  dependsOn: DeployQAInfra
  condition: succeeded('DeployQAInfra')
  jobs:
  - template: templates/deploy-function-template.yml
    parameters:
      variableGroupName: 'FunctionDemo'
      environmentName: 'QA'
