# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to deploy Azure Resources for All Environments for the Azure Function Example Project
# ------------------------------------------------------------------------------------------------------------------------
# Create a variable group for each environment with these variables:
#   environmentCode: 'dev/qa/prod'
#   environmentUpper: 'DEV/QA/PROD'
#   resourceGroupName: 'rg_resourceGroupName'
#   subscriptionName: '<ServiceConnectionName / Subscription Name>'
#   subscriptionId: '<subscriptionId>'
#   location: 'eastus'
#   orgPrefix: '<org - your initials>'
#   appPrefix: 'funcdemo'
#   appSuffix: '1'
#   storageSku: 'Standard_LRS'
#   functionAppSku: 'Y1'
#   functionAppSkuFamily: 'Y'
#   functionAppSkuTier: 'Dynamic'
# ------------------------------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)
pool:
  vmImage: ubuntu-latest

# ------------------------------------------------------------------------------------------------------------------------
#trigger: none # only fire this manually
trigger:
  paths:
    include: 
      - '**/*.yml'
      - '**/*.yaml'
      - '**/*.bicep'

# ----------------------------------------------------------------------------------------------------
stages:
- stage: DeployDEVResources
  displayName: DEV Deploy Resources
  jobs:
  - template: DeployInfrastructureEnvironment.yml
    parameters:
      variableGroupName: 'FunctionDemo-Infra-Dev'
      environmentUpper: 'DEV'
      runDateTime: 'Pipeline-$(Build.BuildNumber)'

# ----------------------------------------------------------------------------------------------------
- stage: DeployQAResources
  displayName: QA Deploy Resources
  dependsOn: DeployDEVResources
  condition: succeeded('DeployDEVResources')
  jobs:
  - template: DeployInfrastructureEnvironment.yml
    parameters:
      variableGroupName: 'FunctionDemo-Infra-QA'
      environmentUpper: 'QA'
      runDateTime: 'Pipeline-$(Build.BuildNumber)'
