# --------------------------------------------------------------------------------
# Pipeline to deploy Azure Resources for All Environments for the Azure Function Example Project
# --------------------------------------------------------------------------------
# Create a variable group for each environment with these variables:
#   environmentCode: 'dev/qa/prod'
#   environmentUpper: 'DEV/QA/PROD'
#   resourceGroupName: 'rg_resourceGroupName'
#   subscriptionName: '<ServiceConnectionName / Subscription Name>'
#   subscriptionId: '<subscriptionId>'
#   location: 'eastus'
#   orgPrefix: '<org - your initials>'
#   appPrefix: 'funcdemo'
#   appSuffix: '1'
#   storageSku: 'Standard_LRS'
#   functionAppSku: 'Y1'
#   functionAppSkuFamily: 'Y'
#   functionAppSkuTier: 'Dynamic'
# --------------------------------------------------------------------------------

trigger: none # fire this manually for now
# trigger:
# - main

pool:
  vmImage: ubuntu-latest

name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)

# --------------------------------------------------------------------------------
stages:
- stage: DeployDEVResources
  displayName: DEV Deploy Resources
  jobs:
  - template: DeployInfrastructureEnvironment.yml
    parameters:
      variableGroupName: 'FunctionDemoDevVariables'
      environmentUpper: 'DEV'
      runDateTime: 'Pipeline-$(Build.BuildNumber)'

- stage: DeployQAResources
  displayName: QA Deploy Resources
  dependsOn: DeployDEVResources
  condition: succeeded('DeployDEVResources')
  jobs:
  - template: DeployInfrastructureEnvironment.yml
    parameters:
      variableGroupName: 'FunctionDemoQAVariables'
      environmentUpper: 'QA'
      runDateTime: 'Pipeline-$(Build.BuildNumber)'
