# ----------------------------------------------------------------------------------------------------
# Template to build Azure Function and create artifacts
# ----------------------------------------------------------------------------------------------------
parameters: 
- name: variableGroupName
  default:  'myVariableGroup'
- name: environmentName
  default:  'DEV'

# ----------------------------------------------------------------------------------------------------
jobs:
- deployment: InitializeBuild${{ parameters.environmentName }}Function
  displayName: Initialize ${{ parameters.environmentName }} Build Function
  environment: ${{ parameters.environmentName }}

- job: Build${{ parameters.environmentName }}Function
  displayName: Build ${{ parameters.environmentName }} Function
  
  variables:
    - group: ${{ parameters.variableGroupName }}

  steps:
  - bash: |
      echo "Build.ArtifactStagingDirectory=$(Build.ArtifactStagingDirectory)"
      echo "System.DefaultWorkingDirectory=$(System.DefaultWorkingDirectory)"
      echo "Build.BuildId=$(Build.BuildId)"
      echo "appPrefix=$(appPrefix)"
    continueOnError: true
    displayName: 'Display Variables'

  - task: DotNetCoreCLI@2
    displayName: 'Build project'
    inputs:
        command: build
        projects: '**/*.csproj'
        arguments: '-- configuration Release'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet publish'
    inputs:
      command: publish
      publishWebProjects: false
      zipAfterPublish: true
      projects: '**/*.csproj'
      arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)/code/'

  - task: PublishBuildArtifacts@1
    displayName: 'Save artifacts'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/code/'
      ArtifactName: 'Code'
      publishLocation: Container                        
