# ----------------------------------------------------------------------------------------------------
# Template to deploy Azure Resources for one environment
# ----------------------------------------------------------------------------------------------------
parameters:
- name: variableGroupName
  default: 'myVariableGroup'
- name: environmentName
  default: 'DEV'
- name: templateFolderName
  default: '.infrastructure/Bicep'
- name: templateFileName
  default: 'main.bicep'

# ----------------------------------------------------------------------------------------------------
jobs:
- deployment: CreateInfra
  displayName: Initialize Create Infra
  environment: ${{ parameters.environmentName }}

- job: CreateInfraJob
  displayName: Create Infrastructure
  variables:
    - group: ${{ parameters.variableGroupName }}
    - name: environmentNameUpper
      value: ${{ upper(parameters.environmentName) }}
    - name: environmentNameLower
      value: ${{ lower(parameters.environmentName) }}
    - name: resourceGroupSuffixBase
      value: '_${{ lower(parameters.environmentName) }}'
    - name: resourceGroupSuffix
      value: ${{ replace(variables.resourceGroupSuffixBase, '_prod', '') }}
    - name: templateFile
      value: '$(Pipeline.Workspace)/s/${{ parameters.templateFolderName }}/${{ parameters.templateFileName }}'
    - name: compiledJsonFile
      value: '${{ parameters.templateFolderName }}/compiled.json'

  steps:
  - bash: |
      resourceGroupName=$(echo "rg_$(appPrefix)$(resourceGroupSuffix)" | tr '[:upper:]' '[:lower:]' | tr '-' '_')
      echo "resourceGroupName=$resourceGroupName"
      echo "##vso[task.setvariable variable=resourceGroupName]$resourceGroupName"
      
      runDateTime=$(echo $(date '+%Y%m%d-%H%M%S'))
      echo "##vso[task.setvariable variable=runDateTime]$runDateTime"
      echo "runDateTime=$runDateTime"
                                   
      runDateTimeZ=$(echo $(date '+%Y%m%dT%H%M%SZ'))
      echo "##vso[task.setvariable variable=runDateTimeZ]$runDateTimeZ"
      echo "runDateTimeZ=$runDateTimeZ"
    displayName: 'Create Variables'
    continueOnError: true

  - bash: |
      echo "subscriptionName=$(subscriptionName)"
      echo "subscriptionId=$(subscriptionId)"
      echo "resourceGroupName=$(resourceGroupName)"
      echo "resourceGroupSuffix=$(resourceGroupSuffix)"
      echo "environmentNameUpper=$(environmentNameUpper)"
      echo "environmentNameLower=$(environmentNameLower)"
      echo "location=$(location)"
      echo "orgPrefix=$(orgPrefix)"
      echo "appPrefix=$(appPrefix)"
      echo "appSuffix=$(appSuffix)"
      echo "storageSku=$(storageSku)"
      echo "functionAppSku=$(functionAppSku)"
      echo "functionAppSkuFamily=$(functionAppSkuFamily)"
      echo "functionAppSkuTier=$(functionAppSkuTier)"
      echo "keyVaultOwnerUserId1=$(keyVaultOwnerUserId1)"
      echo "keyVaultOwnerUserId2=$(keyVaultOwnerUserId2)"
      echo "runDateTime=$(runDateTime)"
      echo "runDateTimeZ=$(runDateTimeZ)"
      echo "templateFile=$(templateFile)"
      echo "compiledJsonFile=$(compiledJsonFile)"
      echo "Resource Group Command:"
      echo "  az group create --name $(resourceGroupName) --location $(location) --tags LastDeployed=$(runDateTime) Organization=$(orgPrefix) Application=$(appPrefix) Environment=$(environmentNameUpper)"
      echo "Bicep Deploy Sample Command:"
      echo "  az deployment group create -n main-deploy-$(runDateTimeZ) --resource-group $(resourceGroupName) --template-file 'main.bicep' --parameters environmentCode $(environmentNameLower) location $(location) orgPrefix $(orgPrefix) appPrefix $(appPrefix) appSuffix $(appSuffix) storageSku $(storageSku) functionAppSku $(functionAppSku) functionAppSkuFamily $(functionAppSkuFamily) functionAppSkuTier $(functionAppSkuTier) keyVaultOwnerUserId1 $(keyVaultOwnerUserId1) keyVaultOwnerUserId2 $(keyVaultOwnerUserId2) runDateTime $(runDateTime)"
    displayName: 'Display Variables'
    continueOnError: true

  # Login is needed if you are pulling Bicep files from an Azure Container Registry
  # -script: az login --service-principal -u $(principalId) -p $(clientSecret) --tenant $(tenantId)
  #   displayName: 'az login'

  # - script: az bicep build --file $(bicepDirectory)$(bicepFileName) --outfile $(compiledJsonFile)
  #   displayName: 'Compile Bicep file'

  - task: AzureCLI@2
    displayName: 'Create Resource Group'
    inputs:
      azureSubscription: $(subscriptionName)
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: az group create --name $(resourceGroupName) --location $(location) --tags LastDeployed=$(runDateTime) Organization=$(orgPrefix) Application=$(appPrefix) Environment=$(environmentNameUpper)

  - task: AzureResourceManagerTemplateDeployment@3
    displayName: 'Publish Bicep Resources'
    inputs:
      csmFile: $(templateFile)
      overrideParameters: >
        -environmentCode $(environmentNameLower)
        -location $(location)
        -orgPrefix $(orgPrefix)
        -appPrefix $(appPrefix)
        -appSuffix $(appSuffix)
        -storageSku $(storageSku)
        -functionAppSku $(functionAppSku)
        -functionAppSkuFamily $(functionAppSkuFamily)
        -functionAppSkuTier $(functionAppSkuTier)
        -keyVaultOwnerUserId1 $(keyVaultOwnerUserId1)
        -keyVaultOwnerUserId2 $(keyVaultOwnerUserId2)
        -runDateTime $(runDateTime)
      deploymentScope: 'Resource Group'
      azureResourceManagerConnection: '$(subscriptionName)'
      subscriptionId: '$(subscriptionId)'
      action: 'Create Or Update Resource Group'
      resourceGroupName: '$(resourceGroupName)'
      location: '$(location)'
      templateLocation: 'Linked artifact'
      deploymentMode: 'Incremental'
