# ----------------------------------------------------------------------------------------------------
# Template to add Azure Secure DevOps Scan
# To enable this, you must add Azure DevOps Extension to your Azure DevOps Organization
# See https://marketplace.visualstudio.com/items?itemName=ms-securitydevops.microsoft-security-devops-azdevops
# ----------------------------------------------------------------------------------------------------
parameters:
- name: environmentName
  default: 'DEV'

jobs:
- deployment: SecurityScanDeployment
  displayName: Initialize Security Scan Deploy
  environment: ${{ parameters.environmentName }}

- job: SecurityScanJob
  displayName: Security Scan Job
  
  steps:
  - task: UseDotNet@2
    displayName: 'Use dotnet 3.1'
    inputs:
      version: 3.1.x
      
  - task: UseDotNet@2
    displayName: 'Use dotnet 6.0'
    inputs:
      version: 6.0.x

  - task: MicrosoftSecurityDevOps@1
    displayName: 'Run Microsoft Security DevOps'
    continueOnError: true
